uint64 id
int32 mode

float32 wheel_width

float32 linear_speed_percent
float32 angular_speed_percent

motion_settings_service/DriverSettings[2] drivers_settings
motion_settings_service/SensorSettings sensor_settings
motion_settings_service/SpdPlanSettings spd_plan_settings

uint8 motor_enable_flags

---

uint64 id
int32 mode

float32 wheel_width

float32 linear_speed_percent
float32 angular_speed_percent

motion_settings_service/DriverSettings[2] drivers_settings
motion_settings_service/SensorSettings sensor_settings
motion_settings_service/SpdPlanSettings spd_plan_settings

uint8 motor_enable_flags
