set(_AMENT_PACKAGE_NAME "pc_software")
set(pc_software_VERSION "0.0.0")
set(pc_software_MAINTAINER "linux <18279657653@139.com>")
set(pc_software_BUILD_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "tf2" "motion_status_msgs" "motion_params_service")
set(pc_software_BUILDTOOL_DEPENDS "ament_cmake")
set(pc_software_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "tf2" "motion_status_msgs" "motion_params_service")
set(pc_software_BUILDTOOL_EXPORT_DEPENDS )
set(pc_software_EXEC_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "tf2" "motion_status_msgs" "motion_params_service")
set(pc_software_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(pc_software_GROUP_DEPENDS )
set(pc_software_MEMBER_OF_GROUPS )
set(pc_software_DEPRECATED "")
set(pc_software_EXPORT_TAGS)
list(APPEND pc_software_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
