; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[esp32_common]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_microros_transport = wifi
board_microros_distro = humble  ; 明确指定ROS 2版本

build_flags =
    -DBOARD_HAS_PSRAM=1
    -DCONFIG_SPIRAM_USE=1
    -DCONFIG_SPIRAM_TYPE_OCTAL=1  ; 强调八进制PSRAM类型
    -DCONFIG_SPIRAM_MODE_OCT=1
    -mfix-esp32-psram-cache-issue  ; 解决PSRAM缓存冲突问题

    -Llib/motion_status_msgs/lib
    -lmotion_status_msgs__rosidl_generator_c
    -lmotion_status_msgs__rosidl_typesupport_c
    -lmotion_status_msgs__rosidl_typesupport_introspection_c
    -lmotion_status_msgs__rosidl_typesupport_microxrcedds_c

    -Llib/motion_settings_service/lib
    -lmotion_settings_service__rosidl_generator_c
    -lmotion_settings_service__rosidl_typesupport_c
    -lmotion_settings_service__rosidl_typesupport_introspection_c
    -lmotion_settings_service__rosidl_typesupport_microxrcedds_c

; -------------esp32-wroom----------------
[env:esp32_wroom]
extends = esp32_common
board = esp32dev

board_build.partitions = huge_app.csv
board_build.ignore_board_partitions = yes
; board_upload.flash_size = 4MB
; board_upload.compress = true
; board_build.flash_size = 4MB

build_flags = ${esp32_common.build_flags} 
    -D esp32_wroom=\"esp32_wroom\"

; -------------esp32-s3----------------
[env:esp32_s3]
extends = esp32_common
board = esp32-s3-devkitc-1

board_build.psram_enable = true
board_build.psram_type = opi
board_build.psram_size = 8MB
board_build.arduino.memory_type = qio_opi  ; 明确指定Flash+PSRAM模式
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_upload.flash_size = 8MB
board_upload.maximum_size = 16777216
board_build.flash_size = 8MB
board_build.arduino.partitions = default_8MB.csv  ; 8MB专用分区表

build_flags = ${esp32_common.build_flags}
    -DCONFIG_ESP32S3_SPIRAM_SUPPORT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D esp32_s3_camera=\"esp32_s3\"